.PHONY: clean default

default:
	svn co --non-interactive https://svn.bluespec.com:8080/bs/customers/trunk/ST_Micro/2005-01_Catania/upcvnt_4/
	cd upcvnt_4 && $(MAKE) synthesis

clean:
	rm -rf upcvnt_4



