// This file automatically generated by SceMiParams::genProbeFile
// DO NOT EDIT
// Generated on: Wed Oct 16 09:36:21 EDT 2013
// Bluespec version: 2013.09.beta4 2013-09-09 32438

#include "bsv_scemi.h"


BSVType *ProbesXactor::createData(unsigned int probeNum, Packet *data, SceMiU64 cycle)
{
  BSVType *type = NULL;
 // No probes are defined!

  return type;
}

unsigned int ProbesXactor::getBitSize(unsigned int probeNum)
{
  return 0;
}
