// Automatically generated by: ::SceMiMsg
// DO NOT EDIT
// C++ Class with SceMi Message passing for type:  PCIE::TLPFirstDWBE

#pragma once

#include "bsv_scemi.h"


/// An alias or typedef name for BitT<4> to TLPFirstDWBE
typedef BitT<4> TLPFirstDWBE ;

