// Automatically generated by: ::SceMiMsg
// DO NOT EDIT
// C++ Class with SceMi Message passing for type:  PCIE::TLPLength

#pragma once

#include "bsv_scemi.h"


/// An alias or typedef name for BitT<10> to TLPLength
typedef BitT<10> TLPLength ;

