// Automatically generated by: ::SceMiMsg
// DO NOT EDIT
// C++ Class with SceMi Message passing for type:  PCIE::TLPRegNum

#pragma once

#include "bsv_scemi.h"


/// An alias or typedef name for BitT<10> to TLPRegNum
typedef BitT<10> TLPRegNum ;

