
install:
	install --backup --owner=root --group=root --mode=0644 50-bluespec.rules /etc/udev/rules.d/
	install -d -m2775 /usr/local/sbin
	install --backup --owner=root --group=root --mode=0755 bluespec-rules.sh /usr/local/sbin/
