// Automaticlly generated by: ::SceMiMsg
// DO NOT EDIT
// C++ Class with SceMi Message passing for Bluespec type:  PowerPrimitives::IsoFailureStruct
// Generated on: Tue Sep 06 13:10:43 EDT 2011
// Bluespec version: 2011.08.beta6 2011-08-31 25135

#pragma once

#include "bsv_scemi.h"
#include "PowerIx.h"

class IsoFailureStruct : public BSVType {
 public:
  BitT<1> m_valid ;
  BitT<1> m_tog ;
  PowerIx m_intnl ;
  PowerIx m_extnl ;

  IsoFailureStruct ()
    : m_valid()
    , m_tog()
    , m_intnl()
    , m_extnl()
  {}

  IsoFailureStruct ( const SceMiMessageDataInterface *msg, unsigned int &off )
    : m_valid(msg, off)
    , m_tog(msg, off)
    , m_intnl(msg, off)
    , m_extnl(msg, off)
  {}

  unsigned int setMessageData (SceMiMessageDataInterface &msg, const unsigned int off=0) const {
    unsigned int running = off;
    running = m_valid.setMessageData( msg, running );
    running = m_tog.setMessageData( msg, running );
    running = m_intnl.setMessageData( msg, running );
    running = m_extnl.setMessageData( msg, running );
    if (running != off + 6 ) {
      std::cerr << "Mismatch in sizes: " << std::dec <<  running << " vs " << (off + 6) << std::endl;
    }
    return running;
  }

  friend std::ostream & operator<< (std::ostream &os, const IsoFailureStruct &obj) {
    BSVType::PutTo * override = lookupPutToOverride ( obj.getClassName() );
    if ( override != 0 ) {
       return override(os, obj );
    }
    os << "{" ;
    os << "extnl " << obj.m_extnl ;os << " " ;
    os << "intnl " << obj.m_intnl ;os << " " ;
    os << "tog " << obj.m_tog ;os << " " ;
    os << "valid " << obj.m_valid ;os << "}" ;
    return os;
  }

  virtual std::ostream & getBitString (std::ostream & os) const {
    m_extnl.getBitString (os);
    m_intnl.getBitString (os);
    m_tog.getBitString (os);
    m_valid.getBitString (os);
  return os;
  }
  

  virtual std::ostream & getBSVType (std::ostream & os) const {
    os << "PowerPrimitives::IsoFailureStruct" ;
    return os;
  }

  virtual unsigned int getBitSize () const {
    return 6;
  }

  virtual const char * getClassName() const {
    return "IsoFailureStruct" ;
  }

  virtual BSVKind getKind() const {
    return BSV_Struct ;
  }

  virtual unsigned int getMemberCount() const {
    return 4;
  };
  
  virtual BSVType * getMember (unsigned int idx) {
    switch (idx) {
      case 0: return & m_extnl;
      case 1: return & m_intnl;
      case 2: return & m_tog;
      case 3: return & m_valid;
      default: std::cerr << "Index error in getMember for class IsoFailureStruct" << std::endl ;
    };
    return 0;
  };
  
  virtual const char * getMemberName (unsigned int idx) const {
    switch (idx) {
      case 0: return "extnl";
      case 1: return "intnl";
      case 2: return "tog";
      case 3: return "valid";
      default: std::cerr << "Index error in getMemberName for class IsoFailureStruct" << std::endl ;
    };
    return 0;
  };
  
  
};

