// Automaticlly generated by: ::SceMiMsg
// DO NOT EDIT
// C++ Class with SceMi Message passing for Bluespec type:  PowerPrimitives::PowerSwitchStruct
// Generated on: Tue Sep 06 13:10:43 EDT 2011
// Bluespec version: 2011.08.beta6 2011-08-31 25135

#pragma once

#include "bsv_scemi.h"
#include "PowerIx.h"

class PowerSwitchStruct : public BSVType {
 public:
  BitT<1> m_valid ;
  BitT<1> m_switchState ;
  PowerIx m_pd ;

  PowerSwitchStruct ()
    : m_valid()
    , m_switchState()
    , m_pd()
  {}

  PowerSwitchStruct ( const SceMiMessageDataInterface *msg, unsigned int &off )
    : m_valid(msg, off)
    , m_switchState(msg, off)
    , m_pd(msg, off)
  {}

  unsigned int setMessageData (SceMiMessageDataInterface &msg, const unsigned int off=0) const {
    unsigned int running = off;
    running = m_valid.setMessageData( msg, running );
    running = m_switchState.setMessageData( msg, running );
    running = m_pd.setMessageData( msg, running );
    if (running != off + 4 ) {
      std::cerr << "Mismatch in sizes: " << std::dec <<  running << " vs " << (off + 4) << std::endl;
    }
    return running;
  }

  friend std::ostream & operator<< (std::ostream &os, const PowerSwitchStruct &obj) {
    BSVType::PutTo * override = lookupPutToOverride ( obj.getClassName() );
    if ( override != 0 ) {
       return override(os, obj );
    }
    os << "{" ;
    os << "pd " << obj.m_pd ;os << " " ;
    os << "switchState " << obj.m_switchState ;os << " " ;
    os << "valid " << obj.m_valid ;os << "}" ;
    return os;
  }

  virtual std::ostream & getBitString (std::ostream & os) const {
    m_pd.getBitString (os);
    m_switchState.getBitString (os);
    m_valid.getBitString (os);
  return os;
  }
  

  virtual std::ostream & getBSVType (std::ostream & os) const {
    os << "PowerPrimitives::PowerSwitchStruct" ;
    return os;
  }

  virtual unsigned int getBitSize () const {
    return 4;
  }

  virtual const char * getClassName() const {
    return "PowerSwitchStruct" ;
  }

  virtual BSVKind getKind() const {
    return BSV_Struct ;
  }

  virtual unsigned int getMemberCount() const {
    return 3;
  };
  
  virtual BSVType * getMember (unsigned int idx) {
    switch (idx) {
      case 0: return & m_pd;
      case 1: return & m_switchState;
      case 2: return & m_valid;
      default: std::cerr << "Index error in getMember for class PowerSwitchStruct" << std::endl ;
    };
    return 0;
  };
  
  virtual const char * getMemberName (unsigned int idx) const {
    switch (idx) {
      case 0: return "pd";
      case 1: return "switchState";
      case 2: return "valid";
      default: std::cerr << "Index error in getMemberName for class PowerSwitchStruct" << std::endl ;
    };
    return 0;
  };
  
  
};

