// Automatically generated by: ::SceMiMsg
// DO NOT EDIT
// C++ Class with SceMi Message passing for type:  TLM3Api::TLMResponseParams

#pragma once

#include "bsv_scemi.h"
#include "TLMCommand.h"
#include "TLMErrorCode.h"
#include "TLMStatus.h"

/// C++ class representing the hardware structure TLM3Api::TLMResponseParams
/// This class has been automatically generated.
class TLMResponseParams : public BSVType {
 public:
  TLMErrorCode m_error ;
  BitT<10> m_transaction_id ;
  TLMStatus m_status ;
  TLMCommand m_command ;

  /// A default constructor
  TLMResponseParams ()
    :  m_error()
    , m_transaction_id()
    , m_status()
    , m_command()
  {}

  /// Constructor for object from a SceMiMessageData object
  /// @param msg -- the scemi message object
  /// @param off -- the starting bit offset, updated to next bit position
  TLMResponseParams ( const SceMiMessageDataInterface *msg, unsigned int &off )
    : m_error(msg, off)
    , m_transaction_id(msg, off)
    , m_status(msg, off)
    , m_command(msg, off)
  {}

  /// Converts this object into its bit representation for sending as a SceMi message
  /// @param msg -- the message object written into
  /// @param off -- bit position off set in message
  /// @return next free bit position for writing
  unsigned int setMessageData (SceMiMessageDataInterface &msg, const unsigned int off=0) const {
    unsigned int running = off;
    running = m_error.setMessageData( msg, running );
    running = m_transaction_id.setMessageData( msg, running );
    running = m_status.setMessageData( msg, running );
    running = m_command.setMessageData( msg, running );
    if (running != off + 17 ) {
      std::cerr << "Mismatch in sizes: " << std::dec <<  running << " vs " << (off + 17) << std::endl;
    }
    return running;
  }

  /// overload the put-to operator for TLMResponseParams
  friend std::ostream & operator<< (std::ostream &os, const TLMResponseParams &obj) {
    BSVType::PutTo * override = lookupPutToOverride ( obj.getClassName() );
    if ( override != 0 ) {
       return override(os, obj );
    }
    os << "{" ;
    os << "command " << obj.m_command ;os << " " ;
    os << "status " << obj.m_status ;os << " " ;
    os << "transaction_id " << obj.m_transaction_id ;os << " " ;
    os << "error " << obj.m_error ;os << "}" ;
    return os;
  }

  /// Adds to the stream the bit representation of this structure object
  /// @param os -- the ostream object which to append
  /// @return the ostream object
  virtual std::ostream & getBitString (std::ostream & os) const {
    m_command.getBitString (os);
    m_status.getBitString (os);
    m_transaction_id.getBitString (os);
    m_error.getBitString (os);
  return os;
  }
  

  /// Accessor for the BSVType name for this object
  /// @param os -- the ostream object which to append
  /// @return the ostream object
  virtual std::ostream & getBSVType (std::ostream & os) const {
    os << "TLM3Api::TLMResponseParams" ;
    return os;
  }

  /// Accessor on the size of the object in bits
  /// @return the bit size
  virtual unsigned int getBitSize () const {
    return 17;
  }

  /// returns the class name for this object
  virtual const char * getClassName() const {
    return "TLMResponseParams" ;
  }

  /// returns the BSVKind for this object
  virtual BSVKind getKind() const {
    return BSV_Struct ;
  }

  /// Accessor for the count of members in object
  virtual unsigned int getMemberCount() const {
    return 4;
  };
  
  /// Accessor to member objects
  /// @param idx -- member index
  /// @return BSVType * to this object or null
  virtual BSVType * getMember (unsigned int idx) {
    switch (idx) {
      case 0: return & m_command;
      case 1: return & m_status;
      case 2: return & m_transaction_id;
      case 3: return & m_error;
      default: std::cerr << "Index error in getMember for class TLMResponseParams" << std::endl ;
    };
    return 0;
  };
  
  /// Accessor for symbolic member names
  /// @param idx -- member index
  /// @return char* to this name or null
  virtual const char * getMemberName (unsigned int idx) const {
    switch (idx) {
      case 0: return "command";
      case 1: return "status";
      case 2: return "transaction_id";
      case 3: return "error";
      default: std::cerr << "Index error in getMemberName for class TLMResponseParams" << std::endl ;
    };
    return 0;
  };
  
  
};

