// clkbuf.v

// Generated using ACDS version 18.0 219

`timescale 1 ps / 1 ps
module clkbuf (
		input  wire  inclk,  //  altclkctrl_input.inclk
		input  wire  ena,    //                  .ena
		output wire  outclk  // altclkctrl_output.outclk
	);

	clkbuf_altclkctrl_180_76rtb7q altclkctrl_0 (
		.inclk  (inclk),  //   input,  width = 1,  altclkctrl_input.inclk
		.ena    (ena),    //   input,  width = 1,                  .ena
		.outclk (outclk)  //  output,  width = 1, altclkctrl_output.outclk
	);

endmodule
