.PHONY: install clean realclean
install clean realclean:
	@$(MAKE) -C core     $@
	@$(MAKE) -C core_tcl $@
	@$(MAKE) -C lumina   $@
	@$(MAKE) -C lumina_socket $@
	@$(MAKE) -C luminaplus $@
	@$(MAKE) -C util     $@
