#!/bin/bash
set -x
set -e
export LM_LICENSE_FILE=27000@license
MY_BLUESPEC=$HOME/bsc/current
export BLUESPECDIR=$MY_BLUESPEC/lib
. /raid/tools/xilinx/latest/ISE_DS/settings64.sh
export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:"$LD_LIBRARY_PATH"
$MY_BLUESPEC/bin/semu
