## Automatically generated by bluetcl -exec makedepend -- Do NOT EDIT
## Date: Wed Jun 19 15:12:19 EDT 2013
## Command: bluetcl -exec makedepend -bdir $(BDIR) *.bs*

$(BDIR)/Azure.bo:	Azure.bsv $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/BGetPut.bo:	BGetPut.bs $(BDIR)/ConfigReg.bo $(BDIR)/GetPut.bo $(BDIR)/Connectable.bo $(BDIR)/ClientServer.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/BRAMCore.bo:	BRAMCore.bsv $(BDIR)/Vector.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/BRAM_Compat.bo:	BRAM_Compat.bsv $(BDIR)/RegFile.bo $(BDIR)/GetPut.bo $(BDIR)/ClientServer.bo $(BDIR)/FIFOF.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/BitUtils.bo:	BitUtils.bsv $(BDIR)/Vector.bo $(BDIR)/List.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/BitonicSort.bo:	BitonicSort.bs $(BDIR)/Vector.bo $(BDIR)/List.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/Boolify.bo:	Boolify.bs $(BDIR)/List.bo $(BDIR)/Vector.bo $(BDIR)/Enum.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/CGetPut.bo:	CGetPut.bs $(BDIR)/FIFOF.bo $(BDIR)/Counter.bo $(BDIR)/ConfigReg.bo $(BDIR)/Connectable.bo $(BDIR)/GetPut.bo $(BDIR)/ClientServer.bo $(BDIR)/Vector.bo $(BDIR)/RegTwo.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/ClientServer.bo:	ClientServer.bs $(BDIR)/Vector.bo $(BDIR)/List.bo $(BDIR)/FIFO.bo $(BDIR)/Counter.bo $(BDIR)/Connectable.bo $(BDIR)/GetPut.bo $(BDIR)/Clocks.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/CompletionBuffer.bo:	CompletionBuffer.bsv $(BDIR)/RegFile.bo $(BDIR)/GetPut.bo $(BDIR)/Counter.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/DPSRAM.bo:	DPSRAM.bs $(BDIR)/RegFile.bo $(BDIR)/GetPut.bo $(BDIR)/ClientServer.bo $(BDIR)/SyncSRAM.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/DReg.bo:	DReg.bs $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/EqFunction.bo:	EqFunction.bs $(BDIR)/Enum.bo $(BDIR)/List.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/Esl_defs.bo:	Esl_defs.bsv $(BDIR)/GetPut.bo $(BDIR)/ClientServer.bo $(BDIR)/Connectable.bo $(BDIR)/Vector.bo $(BDIR)/Clocks.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/FlexBitArith.bo:	FlexBitArith.bs $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/IVec.bo:	IVec.bs $(BDIR)/Vector.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/LFSR.bo:	LFSR.bs $(BDIR)/List.bo $(BDIR)/Vector.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/ListFIFO.bo:	ListFIFO.bs $(BDIR)/FIFO.bo $(BDIR)/FIFOF.bo $(BDIR)/List.bo $(BDIR)/ListReg.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/ListReg.bo:	ListReg.bs $(BDIR)/List.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/Mcp.bo:	Mcp.bs $(BDIR)/Pull.bo $(BDIR)/ConfigReg.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/ModuleAugmented.bo:	ModuleAugmented.bs $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/OInt.bo:	OInt.bs $(BDIR)/Vector.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/OVLAssertions.bo:	OVLAssertions.bsv $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo std_ovl_defines.h
$(BDIR)/PopCount.bo:	PopCount.bs $(BDIR)/List.bo $(BDIR)/Vector.bo $(BDIR)/Wallace.bo $(BDIR)/Tabulate.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/Pull.bo:	Pull.bs $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/Push.bo:	Push.bs $(BDIR)/FIFO.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/RAM.bo:	RAM.bs $(BDIR)/ClientServer.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/RPush.bo:	RPush.bs $(BDIR)/FIFO.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/RegTwo.bo:	RegTwo.bs $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/SPSRAM.bo:	SPSRAM.bs $(BDIR)/RegFile.bo $(BDIR)/GetPut.bo $(BDIR)/ClientServer.bo $(BDIR)/SyncSRAM.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/SRAM.bo:	SRAM.bs $(BDIR)/Vector.bo $(BDIR)/FIFOF.bo $(BDIR)/Counter.bo $(BDIR)/Connectable.bo $(BDIR)/GetPut.bo $(BDIR)/ClientServer.bo $(BDIR)/ConfigReg.bo $(BDIR)/RegTwo.bo $(BDIR)/RAM.bo $(BDIR)/SyncSRAM.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/SRAMFile.bo:	SRAMFile.bs $(BDIR)/RegFile.bo $(BDIR)/GetPut.bo $(BDIR)/ClientServer.bo $(BDIR)/SyncSRAM.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/STRAM.bo:	STRAM.bs $(BDIR)/FIFOF.bo $(BDIR)/Connectable.bo $(BDIR)/GetPut.bo $(BDIR)/ClientServer.bo $(BDIR)/RAM.bo $(BDIR)/SyncSRAM.bo $(BDIR)/SRAM.bo $(BDIR)/TRAM.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/SVA.bo:	SVA.bsv $(BDIR)/List.bo $(BDIR)/Clocks.bo $(BDIR)/PopCount.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/SceMiBlueNoC.bo:	SceMiBlueNoC.bsv $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/SceMiClassic.bo:	SceMiClassic.bsv $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/SplitTRAM.bo:	SplitTRAM.bs $(BDIR)/GetPut.bo $(BDIR)/ClientServer.bo $(BDIR)/TRAM.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/StmtFSM.bo:	StmtFSM.bs $(BDIR)/ClientServer.bo $(BDIR)/ConfigReg.bo $(BDIR)/DReg.bo $(BDIR)/FIFO.bo $(BDIR)/GetPut.bo $(BDIR)/List.bo $(BDIR)/TurboFIFO.bo $(BDIR)/ToString.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/StmtFSMUtil.bo:	StmtFSMUtil.bsv $(BDIR)/List.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/SyncSRAM.bo:	SyncSRAM.bs $(BDIR)/ClientServer.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/TRAM.bo:	TRAM.bs $(BDIR)/FIFO.bo $(BDIR)/ClientServer.bo $(BDIR)/GetPut.bo $(BDIR)/RAM.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/Tabulate.bo:	Tabulate.bs $(BDIR)/List.bo $(BDIR)/Enum.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/ToString.bo:	ToString.bs $(BDIR)/List.bo $(BDIR)/Array.bo $(BDIR)/Vector.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/TriState.bo:	TriState.bsv $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/TurboFIFO.bo:	TurboFIFO.bsv $(BDIR)/FIFO.bo $(BDIR)/FIFOF.bo $(BDIR)/RevertingVirtualReg.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/UIntRange.bo:	UIntRange.bs $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/UniqueWrappers.bo:	UniqueWrappers.bsv $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/Wallace.bo:	Wallace.bs $(BDIR)/Tabulate.bo $(BDIR)/List.bo $(BDIR)/Vector.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/ZBus.bo:	ZBus.bsv $(BDIR)/List.bo $(BDIR)/ZBusUtil.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
$(BDIR)/ZBusUtil.bo:	ZBusUtil.bsv $(BDIR)/List.bo $(BDIR)/Prelude.bo $(BDIR)/PreludeBSV.bo
