#!/usr/bin/perl
################################################################################

# this works on linux to get memory stats via "top"
# do one sample, 
#   set heap size to 3/4 size of physical memory
#   set max size to 4/5 of physical memory

$data = `top -b -n 1`;

# there should be a line like this
# Mem:    516364k total,   234168k used,   282196k free,    25768k buffers
if ($data =~ /Mem:\s+(\d+)k total,/) {
    $h = sprintf "%dM", (($1 * 3) / 4) / 1000;
    $m = sprintf "%dM", (($1 * 4) / 5) / 1000;
    print "+RTS -H$h -M$m -RTS";
}

