PWD := $(shell pwd)
TOP := $(PWD)/../../../../../..

# definitions for platform dependent variables
include $(TOP)/platform.mk

# Install directory
PREFIX ?= $(TOP)/inst

INSTALL ?= $(TOP)/util/install

# -------------------------

.PHONY: all
all:

.PHONY: clean realclean
clean realclean:

.PHONY: install
install:

# -------------------------

